### ISSUE TITLE
Cockpit controls for primary systems

### ISSUE THREAD

**Issue by Rudolf339** [Rudolf339/A-6E#5]
Needed panels:

Right console (those not listed below at least as blank placeholder panels)
- [x] Eng & Fuel Master, Generator Master panel (#3, #4)
- [x] Fuel management panel (#3)
- [ ] Side control panel
- [x] Flaperon popup, APC, anti-skid control panel
- [ ] textures for all above

Other:
- [ ] Digital fuel gauge (#3)
- [ ] Center caution panel
